name: new ec2 Build and Deploy to Docker Hub as docker image

on:
  push:   
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      PORT: ${{ secrets.PORT }}
      REDIS_PORT: ${{ secrets.REDIS_PORT }}
      REDIS_HOST: ${{ secrets.REDIS_HOST }}
      REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}

    steps:
    - name: Check Out Repo
      uses: actions/checkout@v2

    - name: Install Node modules "npm install" 
      run: npm ci

    # - name: Running Tests "npm run test"
    #   run: npm run test

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: pptl8685/socket-service-scs:latest  
        build-args: |
          PORT=${{ secrets.PORT }}
          REDIS_PORT=${{ secrets.REDIS_PORT }}
          REDIS_HOST=${{ secrets.REDIS_HOST }}
          REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }}
          

    - name: Verify Pushed Image
      run: docker pull pptl8685/socket-service-scs:latest 

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST_NEW }}
        username: ${{ secrets.SSH_USERNAME_NEW }}
        key: ${{ secrets.SSH_KEY_NEW }}
        script: |
          sudo docker pull pptl8685/socket-service-scs:latest
          sudo docker stop web-app-scs || true 
          sudo docker rm web-app-scs || true
          sudo docker run -d --name web-app-scs -p ${{ secrets.PORT }}:${{ secrets.PORT }} pptl8685/socket-service-scs:latest
          